// will celan typo3temp files generated by vhs
// https://github.com/gruntjs/grunt-contrib-clean
(function () {
'use strict';

module.exports = {
  alltemp: ['public/typo3temp/assets/**/*'],
  temp: ['public/typo3temp/assets/**/*.js','public/typo3temp/assets/**/*.css','public/typo3temp/assets/**/*.png','public/typo3temp/assets/**/*.svg','public/assets/typo3temp/**/*.jpg'],
  jstemp: ['public/typo3temp/assets/*.js'],
  csstemp: ['public/typo3temp/assets/**/*.css']
};

})(); 